http:
  routers:
    router0:
      rule: Host(`hmdev.mshome.net`)
      entrypoints : 
        - websecure
      service: app
      tls: {}
  services:
    app:
      loadbalancer:
        servers:
          - url: 'http://172.20.163.188:8000'